version: '3'
services:
 app:
  build: ./
  image: csvserverapp:0.1
  ports:
   - "9393:9300"
 prometheus:
  image: prom/prometheus:v2.22.0
  ports:
   - "9090:9090"
  volumes:
   - ./prometheus:/etc/prometheus
  command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

